#!/bin/bash
#sudo adduser martin gpio
#sudo adduser martin spi
#sudo adduser martin i2c
#sudo adduser martin adm
sudo apt-get update
sudo apt-get -y install build-essential python3-dev python3-smbus git python3-setuptools python3-numpy python3-rpi.gpio screen python-configparser python3-requests
cd ~
git clone https://github.com/adafruit/Adafruit_Python_MCP3008.git
cd Adafruit_Python_MCP3008
sudo python3 setup.py install

cd ~
git clone https://github.com/adafruit/Adafruit-Motor-HAT-Python-Library.git
cd Adafruit-Motor-HAT-Python-Library
sudo python3 setup.py install

root@mower2:~# cat /etc/init.d/mower
#!/bin/bash
### BEGIN INIT INFO
# Provides:          mower
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
/bin/su - martin /home/martin/LIAM-on-RPi/bin/start_mower_at_boot

root@mower2:~# update-rc.d mower defaults
